### ISSUE TITLE
Improve internal buffer representation in odb2vtk.py

### ISSUE THREAD

**Issue by sfladi** [Arris-Composites/ODB2VTK#14]
The current internal buffer representation in odb2vtk.py as a string scales poorly with increasing odb-files size.
Repeated appends to the immutable string are expensive and lead to quadratic runtime.
Replacing the internal buffer representation with a mutable object like list or StringIO resolves this issue.

![Fig-RuntimeComparison_elements](https://github.com/Arris-Composites/ODB2VTK/assets/169271542/57531ab6-665b-4219-b0d7-80db8e833034)

**Comment by YangShen398** [comment]
Good job.
