### ISSUE TITLE
Would like to provide information on the version of abaqus that is supported.

### ISSUE THREAD

**Issue by WanQian1997** [Arris-Composites/ODB2VTK#8]
Can the author provide the version of abaqus you are using, I am using abaqus version 2021 when compiling c++ it suggests that a lib file is missing, I guess this is caused by the update of abaqus version.
![image](https://github.com/Arris-Composites/ODB2VTK/assets/108857956/52d15cff-82ed-4554-b55e-cddcc1fd7151)
But the python version works fine

**Comment by YangShen398** [comment]
Hi WanQian1997,

The code was developed based on Abaqus 2019. Now I've made the updates in the C++ version for Abaqus 2023.  Checkout the main branch or abq2023. Details are given in README. Let me know if you still have problems. 

Thanks,
Cam

**Comment by YangShen398** [comment]
Fixed by the commit b32ccc2

**Comment by WanQian1997** [comment]
Thank you very much for your help, I'm not familiar with C++ but I managed to compile and run the programme with your guidance. I see that your update does not involve the program logic itself, so I assume that the current code works for all versions of abaqus. I added all the abaqus2021 lib files as additional dependencies inside visual studio and compiled and linked successfully. I successfully converted the odb file to vtu, thank you!
 I found that when entering the odbfile parameter, if I don't enter the full path, but only a relative path to the current command line path, the program doesn't report an error, but doesn't output anything.

**Comment by YangShen398** [comment]
Good to know that you can compile now. The parsing rules are very rudimentary. At some point I will probably use some well fledged parsing libraries. But this works for now. I am closing this issue because it has been solved. You're welcome to ask any other questions.

Cam
